# Project basics
title: ErikTailor
tagline: My personal blog website
description: This is my personal blog website
author: ErikTailor
logo: /assets/img/eriktailor_logo_dark.webp
locale: hu
baseurl: ""
url: ""
port: 4001

# -----------------------------------------------------

markdown: kramdown

kramdown:
    input: GFM
    syntax_highlighter: rouge

# Defaults
defaults:
    - scope:
          type: posts
          path: _posts
      values:
          is_post: true
          layout: post
          permalink: /blog/:title/
    - scope:
          type: pages
          path: _pages
      values:
          is_post: false
          layout: default

# Exclude files
exclude:
    - CHANGELOG.md
    - LICENSE.txt
    - README.md
    - Gemfile
    - Gemfile.lock
    - .DS_Store
    - .jekyll-cache

# Include files
include: [_pages]

# Livereload
livereload: true

# Sass
sass:
    sourcemap: never
    style: expanded

# Autoprefixer
autoprefixer:
    browsers:
        - last 2 versions

# Minifier
jekyll-minifier:
    exclude: ["sitemap.xml"]
    preserve_php: true
    remove_intertag_spaces: true

# Image optim
imageoptim:
    svgo: false

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# WebP Generation
webp:
    enabled: true
    quality: 80
    img_dir: ["/assets/img/"]
    nested: true

# Tags
tag_page_layout: tagpage
tag_page_dir: tag
tag_page_data:
    sitemap: false

# Staticman
staticman_url: https://eriktailor-staticman-app.herokuapp.com/v2/entry/eriktailor/eriktailor.github.io_source/master/comments

# Plugins
plugins:
    - jekyll-sitemap
    - jekyll-autoprefixer
    - jekyll-minifier
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-webp
